channels:
- channel_id: UCgw_3Epv7swquSZyMDjYHTg
  channel_title: Piotr Cymcyk - Merytorycznie o Finansach
  uploads_id: UUgw_3Epv7swquSZyMDjYHTg
- channel_id: UCAH85XhPoXCxSXUKdwsm0Ig
  channel_title: "Konrad Ksi\u0105\u017Cak - Gie\u0142da, Pieni\u0105dze, Inwestycje"
  uploads_id: UUAH85XhPoXCxSXUKdwsm0Ig
- channel_id: UCh9IhKUDYhf0-IyJII0VClg
  channel_title: "Gie\u0142da Inwestycje Trading"
  uploads_id: UUh9IhKUDYhf0-IyJII0VClg
- channel_id: UCMh0w6OpVi085p81jK5TnzQ
  channel_title: "Tomasz Trela \u2013 Tw\xF3j cz\u0142owiek na Wall Street"
  uploads_id: UUMh0w6OpVi085p81jK5TnzQ
- channel_id: UCbta0n8i6Rljh0obO7HzG9A
  channel_title: Joseph Carlson
  uploads_id: UUbta0n8i6Rljh0obO7HzG9A
- channel_id: UCfCT7SSFEWyG4th9ZmaGYqQ
  channel_title: Joseph Carlson After Hours
  uploads_id: UUfCT7SSFEWyG4th9ZmaGYqQ
- channel_id: UCQvII4zhee-SxRYb4yuPZTg
  channel_title: Emir M
  uploads_id: UUQvII4zhee-SxRYb4yuPZTg
- channel_id: UCn1iWF60wWpCiEAzyaKioDQ
  channel_title: Wolny Arystokrata
  uploads_id: UUn1iWF60wWpCiEAzyaKioDQ
- channel_id: UCLesNX-Yc1bb7mSMefESgSw
  channel_title: Nanalyze
  uploads_id: UULesNX-Yc1bb7mSMefESgSw
- channel_id: UCRvjq3X3HgBvz0ncgPvNYvA
  channel_title: Aria Radnia
  uploads_id: UURvjq3X3HgBvz0ncgPvNYvA
- channel_id: UCt-zZYpkIQMiIMhc4Kkihbg
  channel_title: Drew Cohen
  uploads_id: UUt-zZYpkIQMiIMhc4Kkihbg
- channel_id: UCqqHGGPbhISeKkpEx8676sw
  channel_title: Mr. FIRED Up Wealth
  uploads_id: UUqqHGGPbhISeKkpEx8676sw
- channel_id: UCILwajCs145hxNvB4nckALg
  channel_title: XTB Polska
  uploads_id: UUILwajCs145hxNvB4nckALg
- channel_id: UC3JgUN78v4RX3saWqmCEV1g
  channel_title: Marcin Tuszkiewicz | Inwestowanie & Trading
  uploads_id: UU3JgUN78v4RX3saWqmCEV1g
- channel_id: UC4Qc_TYL6BsqiqXXorBFoaA
  channel_title: "Strefa Inwestor\xF3w"
  uploads_id: UU4Qc_TYL6BsqiqXXorBFoaA
- channel_id: UCASM0cgfkJxQ1ICmRilfHLw
  channel_title: Patrick Boyle
  uploads_id: UUASM0cgfkJxQ1ICmRilfHLw
- channel_id: UCLvnJL8htRR1T9cbSccaoVw
  channel_title: Aswath Damodaran
  uploads_id: UULvnJL8htRR1T9cbSccaoVw
- channel_id: UCCKpicnIwBP3VPxBAZWDeNA
  channel_title: Money & Macro
  uploads_id: UUCKpicnIwBP3VPxBAZWDeNA
- channel_id: UCTNgTBKATr18Z7kR32rKOBw
  channel_title: The Market Huddle
  uploads_id: UUTNgTBKATr18Z7kR32rKOBw
results: 10
